- appium_url: http://127.0.0.1:4723/wd/hub
#Test

- desired_caps_info:
    platformName: Android
    platformVersion: '6.0.1'
    deviceName: xxx
    appPackage: com.langlib.xxx
    appActivity: com.langlib.xxx
    apk_file: 38b40xxxx
    background_time: 5
    unicodeKeyboard: True
    resetKeyboard: True
    #noReset: False
    #conn_type: 6
               # NO_CONNECTION = 0
               # AIRPLANE_MODE = 1
               # WIFI_ONLY = 2
               # DATA_ONLY = 4
               # ALL_NETWORK_ON = 6
- headers:
    Platform: Android
    appkey: CEE_xxxx
    appversion: '1000xxxx'
    AppSecret: 3DB5159C-EB1Exxxxx
    App: cee
    accesstoken: 8xxxx
    Host: appxxxx
    Connection: Keep-Alive
    Accept-Encoding: gzip
    User-Agent: okhttp/3.11.0

- log-Cfg:
    file_name: test.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern:  '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

- mail_cfg:
    user: 185xxx4@163.com
    password: xxxxxxxxx
    smtp: smtp.163.com
    revivers:
        - 185xxxxx@163.com
        - 105xxxx@qq.com
    subject: LangBO_CEE_API_Test_Result_0514
    content:
        - <h1>LangBO_CEE_API_Test_Result_0514</h1>
