- vivox6:
    appium_url:
        url: http://127.0.0.1:4723/wd/hub
    desired_caps:
        platformName: Android
        platformVersion: '6.0.1'
        deviceName: 33ea8e00
        udid: 33ea8e00
        appPackage: com.langlib.ncee
        appActivity: com.langlib.ncee.ui.main.SplashActivity
        unicodeKeyboard: True
        resetKeyboard: True
    headers:
        Platform: Android
        appkey: CEE_AA8F55B916AB
        appversion: '10000005'
        AppSecret: 3DB5159C-EB1E-47FE-8584-47115EF5E443
        App: cee
        accesstoken: 2b9be423-b9ad-4d0e-ade3-ef01c594329d
        Host: appncee.langlib.com
        Connection: Keep-Alive
        Accept-Encoding: gzip
        User-Agent: okhttp/3.11.0

- xiaomi3s:
    appium_url:
        url: http://127.0.0.1:4725/wd/hub
    desired_caps:
        platformName: Android
        platformVersion: '7.1.2'
        deviceName: 007eb32e0804
        udid: 007eb32e0804
        appPackage: com.langlib.ncee
        appActivity: com.langlib.ncee.ui.main.SplashActivity
        unicodeKeyboard: True
        resetKeyboard: True
    headers:
        Platform: Android
        appkey: CEE_AA8F55B916AB
        appversion: '10000004'
        AppSecret: 3DB5159C-EB1E-47FE-8584-47115EF5E443
        App: cee
        accesstoken: d5a1206b-d1bd-4d70-932d-dbededb9b40b
        Host: appncee.langlib.com
        Connection: Keep-Alive
        Accept-Encoding: gzip
        User-Agent: okhttp/3.11.0
